# Generated by Django 4.1.3 on 2023-04-22 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentMarks',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=200)),
                ('DOb', models.DateField()),
                ('PhysicsMarks', models.IntegerField()),
                ('ChemistryMarks', models.IntegerField()),
                ('CsMarks', models.IntegerField()),
            ],
        ),
    ]
