# Generated by Django 4.1.3 on 2023-04-22 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentmarks',
            name='DOb',
            field=models.CharField(max_length=15),
        ),
    ]
